# Generated by Django 3.2.2 on 2021-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
