# Generated by Django 3.2.2 on 2021-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='summary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
